app:
    resource: '@AppBundle/Controller/'
    type: annotation
api:
    resource: '.'
    type: 'api_platform'
    prefix: '/api' # Optional
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin