easy_admin:
    entities:
        Post:
            class: AppBundle\Entity\Post
            list:
                fields:
                    ['id', 'title', 'summary', 'content', 'publishedAt', 'author', 'tags']
            form:
                fields:
                    - { property: 'title' }
                    - { property: 'summary', type: 'ckeditor' }
                    - { property: 'content', type: 'ckeditor' }
                    - { property: 'publishedAt' }
                    - { property: 'status', type: 'choice', label: 'Status', type_options: { choices: '%simple_data.status%',expanded: false, multiple: false } }
                    - { property: 'interesting', type: 'choice', label: 'Interesting', type_options: { choices: '%simple_data.interesting%', expanded: true, multiple: true } }
                    - { property: 'author', type: 'entity', type_options: { multiple: false, class: 'AppBundle\Entity\User', attr: { data-widget: 'select2' } } }
                    - { property: 'tags', type: 'entity', type_options: { multiple: true, class: 'AppBundle\Entity\Tag', attr: { data-widget: 'select2' } } }