easy_admin:
    entities:
        Tag:
            class: AppBundle\Entity\Tag
            list:
                fields:
                    ['id', 'name', 'position']
                sort: ['position', 'ASC']
            search:
                sort: ['name', 'ASC']
            form:
                fields:
                    - { property: 'name' }
                    - { property: 'position' }
